//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta_historico
    {
        public tarjeta_historico()
        {
            this.movimiento_historico = new HashSet<movimiento_historico>();
        }
    
        public int idTarjeta { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Direccion { get; set; }
        public decimal Saldo { get; set; }
        public string Estado { get; set; }
        public short idRuta { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Agente { get; set; }
        public string CodigoTemporal { get; set; }
        public string UltimaModificacion { get; set; }
    
        public virtual ICollection<movimiento_historico> movimiento_historico { get; set; }
        public virtual ruta ruta { get; set; }
    }
}
